### ISSUE TITLE
Q and A

### ISSUE THREAD

**Issue by udochify** [NorhanKhaled/SkillsAcademy-IOT#10]
Please, where is the Question and Answer session happening? Do I just need to post new issue here? How can I see answers to questions asked by other participants? Thanks

**Comment by ranamanse** [comment]
Can I secure data in iot application using steganography techniques ?

**Comment by SapnaSadhwani** [comment]
Do we need to buy sensory boards like raspberry pi 4 for IoT solution development?

**Comment by IfeomaOgbodo** [comment]
1) Is IoT originally intended to be always proactive in the solution it offers or could it also be reactive?
2) Should I be interested in the reference architecture of IoT? The explanation wasn't clear to me.

**Comment by islam3rafah** [comment]
@udochify Q&A is in webex window you can post your questions during the session. Please use github for inquires about labs mainly.

**Comment by islam3rafah** [comment]
> 
> 
> Can I secure data in iot application using steganography techniques ?

I see a lot of challenges doing so, You may refer to https://ieeexplore.ieee.org/abstract/document/8731888

**Comment by islam3rafah** [comment]
> 
> 
>     1. Is IoT originally intended to be always proactive in the solution it offers or could it also be reactive?
> I would not say always to be proactive, but obviously it could be the greatest value of get out of an IoT solution is the solution ability to act autonomously with minimum human intervention.
>     2. Should I be interested in the reference architecture of IoT? It should be covered in more details in the IoT platform session

**Comment by udochify** [comment]
> 
> 
> @udochify Q&A is in webex window you can post your questions during the session. Please use github for inquires about labs mainly.

ok sir
