### ISSUE TITLE
Link to webex session is not written correctly 

### ISSUE THREAD

**Issue by atefhares** [NorhanKhaled/SkillsAcademy-IOT#2]
On the training notes, the written **Event URL** on webex is pointing to an invalid session.
I mean the hyperlink text is correct but the actual link that opens up when text clicked is invalid.

Fix: **COPY** the text, don't click it

--------

I am opening this issue to point this typo out just in case if you did not notice

**Comment by NorhanKhaled** [comment]
Thanks for pointing that out 
it was really helpful
